/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async greet(name: string) : Promise<string> {
    return await TAURI_INVOKE("greet", { name });
},
async takePostChunk(cursor: number | null) : Promise<Result<LikedChunk, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("take_post_chunk", { cursor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AnimatedGifMedia = ({ id: string; url: string; path: string; description: string | null; width: number | null; height: number | null }) & { aspect_ratio: [number, number]; thumb: string; thumb_path: string | null; bitrate: number | null }
export type Article = { id: string; title: string; description: string | null; url: string }
export type Avatar = { url: string; path: string }
export type Card = { title: string | null; description: string | null; url: string }
export type Content = { lang: string; text: string; translation: string | null; expanded_urls: string[] | null }
export type Conversation = { conversation: Post[] }
export type LikedChunk = { cursor: string; data: LikedPost[] }
export type LikedPost = { sortidx: string; post: Post }
export type Media = ({ type: "photo" } & PhotoMedia) | ({ type: "video" } & VideoMedia) | ({ type: "animated_gif" } & AnimatedGifMedia)
export type PhotoMedia = ({ id: string; url: string; path: string; description: string | null; width: number | null; height: number | null })
export type Post = { rest_id: string; created_at: string; author: User; content: Content; media: Media[] | null; quote: QuotePost | null; key_words: string[] | null; replies: Conversation[] | null; card: Card | null; article: Article | null }
export type QuotePost = { rest_id: string; created_at: string; author: User; content: Content; media: Media[] | null; key_words: string[] | null; card: Card | null; article: Article | null }
export type User = { screen_name: string; name: string; avatar: Avatar }
export type VideoMedia = ({ id: string; url: string; path: string; description: string | null; width: number | null; height: number | null }) & { aspect_ratio: [number, number]; thumb: string; thumb_path: string | null; duration_millis: number; bitrate: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
